// SPDX-License-Identifier: AGPL-3.0-or-later

//! OpenAI-compatible model representations for oxideLLM.

use serde::{Deserialize, Serialize};

/// Represents a message in a chat completion request or response.
#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, Eq)]
pub struct Message {
    /// The role of the message author (e.g., "system", "user", "assistant").
    pub role: String,
    /// The content of the message.
    pub content: String,
}

/// Represents a request for chat completion.
#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct ChatCompletionRequest {
    /// The ID of the model to use.
    pub model: String,
    /// A list of messages comprising the conversation so far.
    pub messages: Vec<Message>,
    /// What sampling temperature to use.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub temperature: Option<f32>,
    /// An alternative to sampling with temperature.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub top_p: Option<f32>,
    /// The maximum number of tokens to generate.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_tokens: Option<u32>,
    /// Whether to stream back partial progress.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub stream: Option<bool>,
}

/// Represents a choice in a chat completion response.
#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, Eq)]
pub struct Choice {
    /// The index of the choice in the list.
    pub index: u32,
    /// The message generated by the model.
    pub message: Message,
    /// The reason the model stopped generating.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub finish_reason: Option<String>,
}

/// Represents a response from a chat completion request.
#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, Eq)]
pub struct ChatCompletionResponse {
    /// A unique identifier for the chat completion.
    pub id: String,
    /// The object type, which is always "chat.completion".
    pub object: String,
    /// The Unix timestamp (in seconds) of when the chat completion was created.
    pub created: u64,
    /// The model used for the chat completion.
    pub model: String,
    /// A list of chat completion choices.
    pub choices: Vec<Choice>,
    /// Usage statistics for the completion request.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub usage: Option<Usage>,
}

/// Usage statistics for the completion request.
#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, Eq)]
pub struct Usage {
    /// Number of tokens in the prompt.
    pub prompt_tokens: u32,
    /// Number of tokens in the generated completion.
    pub completion_tokens: u32,
    /// Total number of tokens used.
    pub total_tokens: u32,
}

/// A choice in a streaming chat completion chunk.
#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, Eq)]
pub struct ChoiceChunk {
    /// The index of the choice.
    pub index: u32,
    /// The delta message chunk.
    pub delta: DeltaMessage,
    /// The reason why stream ended.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub finish_reason: Option<String>,
}

/// The delta message containing changed content.
#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, Eq)]
pub struct DeltaMessage {
    /// The role of the message author.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub role: Option<String>,
    /// The contents of the chunk.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
}

/// A streaming chunk of chat completion response.
#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, Eq)]
pub struct ChatCompletionChunk {
    /// Unique identifier for the chunk.
    pub id: String,
    /// Object type, always "chat.completion.chunk".
    pub object: String,
    /// Unix timestamp in seconds.
    pub created: u64,
    /// Model name.
    pub model: String,
    /// Choice deltas.
    pub choices: Vec<ChoiceChunk>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_chat_completion_request_serde() {
        let request = ChatCompletionRequest {
            model: "gpt-4".to_string(),
            messages: vec![Message {
                role: "user".to_string(),
                content: "Hello".to_string(),
            }],
            temperature: Some(0.7),
            top_p: None,
            max_tokens: Some(100),
            stream: Some(true),
        };

        let json = serde_json::to_string(&request).unwrap();
        let parsed: ChatCompletionRequest = serde_json::from_str(&json).unwrap();
        assert_eq!(request, parsed);
        assert!(json.contains("\"model\":\"gpt-4\""));
        assert!(json.contains("\"stream\":true"));
        assert!(!json.contains("top_p"));
    }

    #[test]
    fn test_chat_completion_response_serde() {
        let response = ChatCompletionResponse {
            id: "chatcmpl-123".to_string(),
            object: "chat.completion".to_string(),
            created: 1677652288,
            model: "gpt-4".to_string(),
            choices: vec![Choice {
                index: 0,
                message: Message {
                    role: "assistant".to_string(),
                    content: "Hello there!".to_string(),
                },
                finish_reason: Some("stop".to_string()),
            }],
            usage: Some(Usage {
                prompt_tokens: 9,
                completion_tokens: 12,
                total_tokens: 21,
            }),
        };

        let json = serde_json::to_string(&response).unwrap();
        let parsed: ChatCompletionResponse = serde_json::from_str(&json).unwrap();
        assert_eq!(response, parsed);
    }

    #[test]
    fn test_streaming_chunk_serde() {
        let chunk = ChatCompletionChunk {
            id: "chatcmpl-123".to_string(),
            object: "chat.completion.chunk".to_string(),
            created: 1677652288,
            model: "gpt-4".to_string(),
            choices: vec![ChoiceChunk {
                index: 0,
                delta: DeltaMessage {
                    role: Some("assistant".to_string()),
                    content: Some("Hello".to_string()),
                },
                finish_reason: None,
            }],
        };

        let json = serde_json::to_string(&chunk).unwrap();
        let parsed: ChatCompletionChunk = serde_json::from_str(&json).unwrap();
        assert_eq!(chunk, parsed);
    }

    #[test]
    fn test_request_with_optional_fields() {
        let request_min = ChatCompletionRequest {
            model: "llama-3".to_string(),
            messages: vec![Message {
                role: "system".to_string(),
                content: "You are a helpful assistant.".to_string(),
            }],
            temperature: None,
            top_p: None,
            max_tokens: None,
            stream: None,
        };

        let json = serde_json::to_string(&request_min).unwrap();
        let parsed: ChatCompletionRequest = serde_json::from_str(&json).unwrap();
        assert_eq!(request_min, parsed);
        assert!(!json.contains("temperature"));
        assert!(!json.contains("stream"));
    }

    #[test]
    fn test_malformed_json_handling() {
        let malformed = r#"{"model": "gpt-4", "messages": "#;
        let result: Result<ChatCompletionRequest, _> = serde_json::from_str(malformed);
        assert!(result.is_err());
    }
}
