name: Sponsors README

on:
  sponsorship:
    types: [created, edited, cancelled]
  schedule:
    - cron: '0 0 * * *' # Every day at midnight
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7

      - name: Update Sponsors in README
        uses: JamesIves/github-sponsors-readme-action@v1
        with:
          token: ${{ secrets.SPONSORS_TOKEN }}
          file: 'README.md'

      - name: Commit & Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update sponsors in README [skip ci]"
